### ISSUE TITLE
Prototipo RA

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-irving-1#1]
[Prototipo App.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-irving-1/files/14394743/Prototipo.App.pdf)

**Comment by magaly1311** [comment]
Excelente : 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
